CREATE DATABASE QLBCVT1
GO
USE QLBCVT1

-- Done
CREATE TABLE CHINHANH
(
   BRANCH_CODE NVARCHAR(5) PRIMARY KEY,
   BRANCH_ADDRESS NVARCHAR(200) NOT NULL,
   BRANCH_PHONE INT
)
-- Done
CREATE TABLE KHACHHANG
(
   CUS_CODE NVARCHAR(7) PRIMARY KEY,
   CUS_NAME NVARCHAR(250),
   CUS_BIRTH DATETIME,
   CUS_PHONE CHAR(10),
   CUS_ADDRESS NVARCHAR(250) NOT NULL,
   BRANCH_CODE NVARCHAR(5),
   CUS_STATUS NVARCHAR(50)
)


CREATE TABLE SODUKH
(
   CUS_CODE NVARCHAR(7) REFERENCES KHACHHANG(CUS_CODE),
   PRIMARY KEY(CUS_CODE),
   SD_ACCOUNTBALANCE FLOAT NOT NULL
)
-- Done
CREATE TABLE HOATDONG
(
   HD_CODE NVARCHAR(7)
   PRIMARY KEY(HD_CODE),
   CUS_CODE NVARCHAR(7) FOREIGN KEY REFERENCES KHACHHANG(CUS_CODE),

   HOATDONG_DAY DATETIME,
   HOATDONG_DESC NVARCHAR(255) NOT NULL,
   --nghe/ gọi/ nộp tiền
   HOATDONG_PRICE FLOAT
   --GIÁ CẢ, NẾU LÀ TRỪ THÌ CÓ TRỪ TRƯỚC CÒN NỘP THÌ ĐỂ SỐ BTH
)
-- Done
CREATE TABLE NHANVIEN
(
    STAFF_CODE NVARCHAR(5) PRIMARY KEY,
	STAFF_NAME NVARCHAR(250) NOT NULL,
	STAFF_PHONE CHAR(10) NOT NULL,
	STAFF_ADDRESS NVARCHAR(255),
	BRANCH_CODE NVARCHAR(5) FOREIGN KEY REFERENCES CHINHANH(BRANCH_CODE)
)
-- Done
CREATE TABLE DICHVU
(
     SERVICE_CODE NVARCHAR(5) PRIMARY KEY,
	 SERVICE_DESCRIPTION_NAME NVARCHAR(250) NOT NULL,
	 SERVICE_PRICE FLOAT NOT NULL,
	 SERVICE_DURATION NVARCHAR(15),
	 SERVICE_DESC NVARCHAR(255),
	 SERVICE_TYPE NVARCHAR(50)
)
-- Hop dong only for afterpaid
-- Done
CREATE TABLE HOPDONG
(
     CONTRACT_CODE NVARCHAR(5) PRIMARY KEY,
	 CUS_CODE NVARCHAR(7) FOREIGN KEY REFERENCES KHACHHANG(CUS_CODE),
	 SERVICE_CODE NVARCHAR(5) FOREIGN KEY REFERENCES DICHVU(SERVICE_CODE),
	 CONTRACT_STATUS NVARCHAR(100)
)
-- Done
CREATE TABLE CTDK
(
     REG_CODE NVARCHAR(10) PRIMARY KEY,
	 CONTRACT_CODE NVARCHAR(5) FOREIGN KEY  REFERENCES HOPDONG(CONTRACT_CODE),
	 REG_END DATETIME NOT NULL,
	 REG_PAYMENT NVARCHAR(20) NOT NULL
)

CREATE TABLE HOADON
(
     INV_CODE NVARCHAR(5) PRIMARY KEY,
	 STAFF_CODE NVARCHAR(5) FOREIGN KEY REFERENCES NHANVIEN(STAFF_CODE),
	 CUS_CODE NVARCHAR(7) FOREIGN KEY REFERENCES KHACHHANG(CUS_CODE),
	 INV_DAY DATETIME,
	 INV_TOTAL INT
)

CREATE TABLE CTHD
(
     LINE_CODE NVARCHAR(5) PRIMARY KEY,
	 INV_CODE NVARCHAR(5) FOREIGN KEY REFERENCES HOADON(INV_CODE),
	 SERVICE_CODE NVARCHAR(5) FOREIGN KEY REFERENCES DICHVU(SERVICE_CODE),
)
-- Done
CREATE TABLE LOAILOI
(
     TE_CODE NVARCHAR(6) PRIMARY KEY,
	 SERVICE_CODE NVARCHAR(5),
	 ERROR_DES NVARCHAR(250)
)

-- Done
CREATE TABLE LOI
(
      ERROR_CODE NVARCHAR(6) PRIMARY KEY,
	  TE_CODE NVARCHAR(6) FOREIGN KEY REFERENCES LOAILOI(TE_CODE),
	  CUSCODE NVARCHAR(7) FOREIGN KEY REFERENCES KHACHHANG(CUS_CODE),
	  ERROR_DESC NVARCHAR(1024) NOT NULL
)
-- Done
CREATE TABLE COMMENT
(
      COMMENT_CODE NVARCHAR(5) PRIMARY KEY,
      CUS_CODE NVARCHAR(7) FOREIGN KEY REFERENCES KHACHHANG(CUS_CODE),
      COMMENT_DESC NVARCHAR(1024),
	  COMMENT_RESPOND NVARCHAR(1024),
	  COMMENT_STAR INT CHECK(COMMENT_STAR >= 0 AND COMMENT_STAR <= 5) DEFAULT 5,
	  SERVICE_CODE NVARCHAR(5) FOREIGN KEY REFERENCES DICHVU(SERVICE_CODE),

)