CREATE OR ALTER VIEW KHACHHANG_VIEW AS
SELECT TOP 10 SUM(HOADON.INV_TOTAL) AS TONG_GIA_TIEN, KHACHHANG.CUS_CODE
FROM HOADON 
JOIN KHACHHANG ON HOADON.CUS_CODE = KHACHHANG.CUS_CODE
GROUP BY KHACHHANG.CUS_CODE
ORDER BY TONG_GIA_TIEN DESC;

SELECT * FROM KHACHHANG_VIEW