CREATE OR ALTER VIEW DICHVU_VIEW AS
SELECT TOP 10 COUNT(HOPDONG.CONTRACT_CODE) AS TONG_DANG_KY, DICHVU.SERVICE_CODE
FROM HOPDONG
JOIN DICHVU ON HOPDONG.SERVICE_CODE = DICHVU.SERVICE_CODE
GROUP BY DICHVU.SERVICE_CODE
ORDER BY TONG_DANG_KY DESC;

SELECT * FROM DICHVU_VIEW