-- CHANGE THE DATE TO SEE OTHER PERIODS 
 CREATE OR ALTER VIEW THUTIEN_VIEW AS
 SELECT HOPDONG.CUS_CODE, KHACHHANG.CUS_NAME, KHACHHANG.CUS_ADDRESS, CTDK.REG_END
 FROM HOPDONG
 JOIN KHACHHANG ON HOPDONG.CUS_CODE = KHACHHANG.CUS_NAME
 JOIN CTDK ON HOPDONG.CONTRACT_CODE = CTDK.CONTRACT_CODE
 WHERE REG_END BETWEEN '2021-01-26' AND '2021-05-05';

 SELECT * FROM THUTIEN_VIEW;