 CREATE OR ALTER VIEW TRATRUOC_VIEW AS
 SELECT HOPDONG.CUS_CODE, DICHVU.SERVICE_DESCRIPTION_NAME, DICHVU.SERVICE_DESC
 FROM HOPDONG
 JOIN DICHVU ON HOPDONG.SERVICE_CODE = DICHVU.SERVICE_CODE
 WHERE SERVICE_DESC = 'TRA_TRUOC'

 SELECT * FROM TRATRUOC_VIEW;