--Khách A đang sử dụng dịch vụ gì
SELECT DICHVU.SERVICE_CODE, SERVICE_DESCRIPTION_NAME
FROM KHACHHANG JOIN HOPDONG ON KHACHHANG.CUS_CODE= HOPDONG.CUS_CODE
JOIN DICHVU ON HOPDONG.SERVICE_CODE = DICHVU.SERVICE_CODE
WHERE KHACHHANG.CUS_NAME= N'BÙI ĐỨC TRẦN HOÀN' AND HOPDONG.CONTRACT_STATUS = 'ACTIVE'