SELECT TOP(1) KHACHHANG.CUS_CODE, CUS_NAME, COUNT(COMMENT_CODE) AS TIMES
FROM KHACHHANG JOIN COMMENT ON KHACHHANG.CUS_CODE = COMMENT.CUS_CODE
GROUP BY KHACHHANG.CUS_CODE, CUS_NAME
ORDER BY COUNT(COMMENT_CODE) DESC