SELECT TOP(5) DICHVU.SERVICE_CODE, SERVICE_DESCRIPTION_NAME, COUNT(CTDK.REG_CODE) AS TIMES
FROM DICHVU FULL JOIN HOPDONG ON DICHVU.SERVICE_CODE= HOPDONG.SERVICE_CODE
FULL JOIN CTDK ON HOPDONG.CONTRACT_CODE = CTDK.CONTRACT_CODE
GROUP BY DICHVU.SERVICE_CODE, SERVICE_DESCRIPTION_NAME
ORDER BY COUNT(CTDK.REG_CODE) DESC