-- ADJUST THE NAME TO SEE OTHER CUSTOMERS
SELECT NHANVIEN.STAFF_CODE, INV_TOTAL
FROM HOADON JOIN NHANVIEN ON HOADON.STAFF_CODE = NHANVIEN.STAFF_CODE
JOIN KHACHHANG ON HOADON.CUS_CODE = KHACHHANG.CUS_CODE
WHERE KHACHHANG.CUS_NAME = N'BÙI ĐỨC TRẦN HOÀN'