SELECT KHACHHANG.CUS_CODE, CUS_NAME, CUS_PHONE
FROM KHACHHANG FULL JOIN HOPDONG ON KHACHHANG.CUS_CODE = HOPDONG.CUS_CODE
FULL JOIN DICHVU ON HOPDONG.SERVICE_CODE = DICHVU.SERVICE_CODE
WHERE SERVICE_DESCRIPTION_NAME LIKE 'SMS'