CREATE OR ALTER PROCEDURE CHECK_CONTRACT
@CUS_CODE NVARCHAR(7),
@SERVICE_CODE NVARCHAR(5)

AS
BEGIN
     IF EXISTS(SELECT CUS_CODE FROM KHACHHANG WHERE CUS_CODE = @CUS_CODE)
	    IF EXISTS(SELECT SERVICE_CODE FROM HOPDONG WHERE SERVICE_CODE = @SERVICE_CODE)
	    PRINT N'KHÁCH HÀNG ' + CAST(@CUS_CODE AS NVARCHAR(7)) + N' ĐÃ ĐĂNG KÝ DỊCH VỤ ' + CAST(@SERVICE_CODE AS NVARCHAR(5))
	    ELSE
	    PRINT N'KHÁCH HÀNG CHƯA ĐĂNG KÝ DỊCH VỤ ' + CAST(@SERVICE_CODE AS NVARCHAR(5))
	ELSE
	PRINT 'KHÁCH HÀNG CHƯA ĐĂNG KÝ THÀNH VIÊN'

END
GO
EXECUTE CHECK_CONTRACT'KH01', 'DV500'
