CREATE OR ALTER PROCEDURE MEET_DEADLINE_STATUS
AS 
BEGIN
DECLARE @reg_end as DATETIME
DECLARE @reg_payment as NVARCHAR(25)
DECLARE @reg_code as NVARCHAR(10)
DECLARE @contract_code as NVARCHAR(5)
DECLARE @late as DATETIME
DECLARE @today as DATETIME

SET @today = GETDATE()
SET @late = dateadd(day,-10,@today)
DECLARE CHECK_LATE_DEADLINE CURSOR FOR
SELECT REG_CODE, CONTRACT_CODE, REG_END, REG_PAYMENT FROM CTDK

OPEN CHECK_LATE_DEADLINE
FETCH NEXT FROM CHECK_LATE_DEADLINE
	INTO @reg_code,@contract_code, @reg_end, @reg_payment
WHILE @@FETCH_STATUS = 0
BEGIN
IF @reg_end <= @late
	BEGIN
	IF @reg_payment = N'NOT COMPLETED'
		UPDATE CTDK SET REG_PAYMENT = 'LATE 10 DAYS' WHERE CURRENT OF CHECK_LATE_DEADLINE
	IF @reg_payment = 'LATE 10 DAYS'
		BEGIN
		UPDATE CTDK SET REG_PAYMENT = 'LATE 20 DAYS' WHERE CURRENT OF CHECK_LATE_DEADLINE
		UPDATE HOPDONG SET CONTRACT_STATUS = 'INACTIVE'
		WHERE CONTRACT_CODE= @contract_code
		END
	END
	
FETCH NEXT FROM CHECK_LATE_DEADLINE
	INTO  @reg_code, @contract_code, @reg_end, @reg_payment
END
CLOSE CHECK_LATE_DEADLINE
DEALLOCATE CHECK_LATE_DEADLINE
END